desc: noDesc
log_dir: long_run_properties_2024-11-28__08_45_08
device: cpu
seed: 0
validate_every: 1000
checkpoint_every: 100
store_all_checkpoints: true
print_every: 1
start_at_step: 0
num_final_gen_steps: null
num_validation_gen_steps: 1
num_training_steps: 100
num_workers: 0
hostname: null
pickle_mp_messages: false
git_hash: f106cde
overwrite_existing_exp: false
algo:
  method: TB
  num_from_policy: 64
  num_from_dataset: 0
  valid_num_from_policy: 64
  valid_num_from_dataset: 0
  max_len: 128
  max_nodes: 6
  max_edges: 128
  illegal_action_logreward: -1.0
  train_random_action_prob: 0.0
  train_det_after: null
  valid_random_action_prob: 0.0
  sampling_tau: 0.9
  tb:
    bootstrap_own_reward: false
    epsilon: null
    reward_loss_multiplier: 1.0
    variant: TB
    do_correct_idempotent: false
    do_parameterize_p_b: false
    do_predict_n: false
    do_sample_p_b: false
    do_length_normalize: false
    subtb_max_len: 128
    Z_learning_rate: 0.0001
    Z_lr_decay: 50000.0
    cum_subtb: true
    loss_fn: MSE
    loss_fn_par: 1.0
    n_loss: none
    n_loss_multiplier: 1.0
    backward_policy: Uniform
  moql:
    gamma: 1.0
    num_omega_samples: 32
    num_objectives: 2
    lambda_decay: 10000
    penalty: -10.0
  a2c:
    entropy: 0.01
    gamma: 1.0
    penalty: -10.0
  fm:
    epsilon: 1.0e-38
    balanced_loss: false
    leaf_coef: 10.0
    correct_idempotent: false
  sql:
    alpha: 0.01
    gamma: 1.0
    penalty: -10.0
model:
  num_layers: 3
  num_emb: 128
  dropout: 0.0
  graph_transformer:
    num_heads: 2
    ln_type: pre
    num_mlp_layers: 0
    concat_heads: true
  seq_transformer:
    num_heads: 2
    posenc: Rotary
opt:
  opt: adam
  learning_rate: 0.0001
  lr_decay: 20000.0
  weight_decay: 1.0e-08
  momentum: 0.9
  clip_grad_type: norm
  clip_grad_param: 10.0
  adam_eps: 1.0e-08
replay:
  use: false
  capacity: null
  warmup: null
  hindsight_ratio: 0.0
  num_from_replay: null
  num_new_samples: null
task:
  qm9:
    h5_path: ./data/qm9/qm9.h5
    model_path: ./data/qm9/qm9_model.pt
  qm9_moo:
    n_valid: 15
    n_valid_repeats: 128
    objectives:
    - gap
    - qed
    - sa
    online_pareto_front: true
  seh:
    reduced_frag: false
  seh_moo:
    n_valid: 15
    n_valid_repeats: 128
    objectives:
    - seh
    - qed
    - sa
    - mw
    log_topk: false
    online_pareto_front: true
cond:
  valid_sample_cond_info: true
  temperature:
    sample_dist: uniform
    dist_params:
    - 0.5
    - 32
    num_thermometer_dim: 32
  moo:
    num_objectives: 2
    num_thermometer_dim: 16
  weighted_prefs:
    preference_type: dirichlet
    preference_param: 1.5
  focus_region:
    focus_type: centered
    use_steer_thermomether: false
    focus_cosim: 0.98
    focus_limit_coef: 0.1
    focus_model_training_limits:
    - 0.25
    - 0.75
    focus_model_state_space_res: 30
    max_train_it: 20000
